* Guided Essay Writing:
** The question
1) Break the question into *vocabulary*, look at denotations, connotations, synonyms, antonyms.
2) Look at Real World Contexts: Historical, Political, Philosphical, e.t.c. Provides nuance
3) Knowledge, quotes. 2 to 3 points, each being a comparison / similarity.

** Thesis
*** Guiding Questions
Look for tension and connection.
Where are the texts similar and different? why?

*** Possible structures
While The Memory Police …, The Crucible …
Despite . differences ...

*** Examples
Despite historical differences, both texts present how those who are ignorant or 'not knowing' are vulnerable to being exploited by those in control of knowledge as a means to power.

Despite historical and political differences, both texts present how its favourable to not know than know.

Despite the dichotomy between the historical differences, both texts

** Points
1) Controlled + Constructed ignorance
   - Ch2 birds
   - ACT 1 - woods; Abi's plot; Theocracy?

2) Wilful or performed ignorance
   - Ch19, book burnings
   - ACT 3, court, Elizabeth Proctor

3) Counter: those who know
   - R, Mother
   - Hale ACT 1 -> ACT 3. Knowledge causing guilt or punishment.
